//! jaligner port: NeedlemanWunschGotoh(Banded), AlignmentStats, ZipperAlignment.
//!
//! Faithful line-by-line port of Butterfly's bundled jaligner sources
//! (NeedlemanWunschGotoh.java / NeedlemanWunschGotohBanded.java / Alignment.java /
//! AlignmentStats.java / ZipperAlignment.java), including the following quirks that
//! are kept verbatim (marked QUIRK in comments):
//!  1. Sequences are sorted so the longer is s1 (rows); names swap with them.
//!  2. All DP arithmetic is f32 (Java float), including tie comparisons via `==`.
//!  3. The reported score is `v[n-1]` while traceback starts at the cell of the
//!     maximum observed v (maxi, maxj) — these can differ.
//!  4. At end of each row, `vDiagonal` is reset to 0 (not the true upper-left
//!     value) and `v[1..n)` are initialised to 0 (loose first row).
//!  5. Horizontal-gap extension ties (`h - e >= v[j-1] - o`) prefer extension.
//!  6. Banded: cells outside the band keep `pointers = DIRECTION_INIT (=4)`;
//!     traceback stops upon hitting DIRECTION_INIT (early truncation possible).
//!  7. Banded: the `pointers[0] = STOP` assignment is overwritten by the
//!     fill-everything-with-DIRECTION_INIT loop, so STOP is unreachable there.
//!  8. ZipperAlignment.doZipperAlignmentAnchorRight compares `seqA[i] == seqB[i]`
//!     (both indexed by the shorter-sequence index `i`) — Java bug kept verbatim.

/// Traceback directions (jaligner.Directions).
const STOP: u8 = 0;
const LEFT: u8 = 1;
const DIAGONAL: u8 = 2;
const UP: u8 = 3;
/// jaligner NeedlemanWunschGotohBanded.DIRECTION_INIT.
const DIRECTION_INIT: u8 = 4;

const GAP: u8 = b'-';

/// Result of a pairwise alignment (port of jaligner.Alignment essentials).
///
/// `start1`/`start2` are the 0-based row/col at which traceback stopped, i.e.
/// `Alignment.getStart1()/getStart2()` in Java (number of leading original
/// characters not covered by the traceback).
#[derive(Debug, Clone, PartialEq)]
pub struct AlignmentResult {
    pub aligned1: Vec<u8>,
    pub aligned2: Vec<u8>,
    pub score: f32,
    pub start1: usize,
    pub start2: usize,
}

/// Alignment statistics (port of Butterfly's AlignmentStats, NW flavour).
#[derive(Debug, Clone, Default, PartialEq)]
pub struct AlignmentStats {
    pub matches: usize,
    pub mismatches: usize,
    /// internal gaps (columns within [left_bound, right_bound] containing a gap)
    pub gaps: usize,
    pub alignment_length: usize,
    pub max_internal_gap_length: usize,
    pub left_gap_length: usize,
    pub right_gap_length: usize,
    /// all gaps (internal + terminal) and mismatches
    pub total_not_matched: usize,
    /// -1 when no aligned bases
    pub left_bound: i64,
    pub right_bound: i64,
    /// port of alignedBaseCounter (per input sequence, in sorted order 1/2)
    pub count1: usize,
    pub count2: usize,
}

/// Scoring matrix generated by MatrixGenerator.generate(match, mismatch):
/// `N` matches everything (QUIRK: `i == 'N' || j == 'N'` scores as match).
#[inline]
fn score(a: u8, b: u8, match_s: f32, mismatch: f32) -> f32 {
    if a == b || a == b'N' || b == b'N' {
        match_s
    } else {
        mismatch
    }
}

/// Java `maximum(float a, float b, float c)` verbatim (tie order matters).
#[inline]
fn maximum(a: f32, b: f32, c: f32) -> f32 {
    if a > b {
        if a > c {
            a
        } else {
            c
        }
    } else if b > c {
        b
    } else {
        c
    }
}

/// Shared DP construction for banded and unbanded Needleman-Wunsch-Gotoh.
///
/// `bandwidth == None` runs the plain full-matrix version
/// (NeedlemanWunschGotoh); `Some(bandwidth)` runs the banded version
/// (NeedlemanWunschGotohBanded).
struct DpOutput {
    maxi: usize,
    maxj: usize,
    score: f32,
    pointers: Vec<u8>,
    lengths: Vec<i32>,
}

fn construct(
    a1: &[u8],
    a2: &[u8],
    match_s: f32,
    mismatch: f32,
    o: f32,
    e: f32,
    bandwidth: Option<usize>,
) -> DpOutput {
    let m = a1.len() + 1;
    let n = a2.len() + 1;

    let mut pointers = vec![0u8; m * n];
    let mut lengths = vec![0i32; m * n];

    if bandwidth.is_some() {
        // QUIRK(7): pointers[0] = STOP is immediately overwritten; every cell
        // starts as DIRECTION_INIT, boundaries re-set below.
        for p in pointers.iter_mut() {
            *p = DIRECTION_INIT;
        }
    } else {
        pointers[0] = STOP;
    }
    // Boundary init: first column UP/lengths=i, first row LEFT/lengths=j.
    let mut k = n;
    for i in 1..m {
        pointers[k] = UP;
        lengths[k] = i as i32;
        k += n;
    }
    for j in 1..n {
        pointers[j] = LEFT;
        lengths[j] = j as i32;
    }

    // QUIRK(4): loose first row — v[1..n) = 0, g[1..n) = -inf, vDiagonal = 0.
    let mut v = vec![0f32; n];
    let mut g = vec![f32::NEG_INFINITY; n];
    let mut v_diagonal = 0f32;
    let mut h = f32::NEG_INFINITY;
    let mut length_of_horizontal_gap: i32 = 0;
    let mut length_of_vertical_gap = vec![0i32; n];

    let mut maximum_score = f32::NEG_INFINITY;
    let mut maxi = 0usize;
    let mut maxj = 0usize;

    let half_band = bandwidth.map(|bw| usize::max(bw / 2, 1));

    for i in 1..m {
        let k = i * n;
        v[0] = -o - ((i - 1) as f32) * e;

        let (band_start, band_end) = match half_band {
            // QUIRK(6): band is [max(1, i-half), min(n, i+half)) — half-open,
            // cells outside keep DIRECTION_INIT pointers.
            Some(half) => (
                usize::max(1, i.saturating_sub(half)),
                usize::min(n, i + half),
            ),
            None => (1, n),
        };

        for j in band_start..band_end {
            let l = k + j;
            let similarity = score(a1[i - 1], a2[j - 1], match_s, mismatch);
            let f = v_diagonal + similarity;

            // Which cell from the left? QUIRK(5): >= prefers extension.
            if h - e >= v[j - 1] - o {
                h -= e;
                length_of_horizontal_gap += 1;
            } else {
                h = v[j - 1] - o;
                length_of_horizontal_gap = 1;
            }
            // Which cell from above?
            if g[j] - e >= v[j] - o {
                g[j] -= e;
                length_of_vertical_gap[j] += 1;
            } else {
                g[j] = v[j] - o;
                length_of_vertical_gap[j] = 1;
            }

            v_diagonal = v[j];
            v[j] = maximum(f, g[j], h);
            if v[j] > maximum_score {
                maximum_score = v[j];
                maxi = i;
                maxj = j;
            }

            if v[j] == f {
                pointers[l] = DIAGONAL;
            } else if v[j] == g[j] {
                pointers[l] = UP;
                lengths[l] = length_of_vertical_gap[j];
            } else if v[j] == h {
                pointers[l] = LEFT;
                lengths[l] = length_of_horizontal_gap;
            } else {
                panic!("didn't determine direction");
            }
        }

        // Reset. QUIRK(4): vDiagonal reset to 0, not the true upper-left value.
        h = f32::NEG_INFINITY;
        v_diagonal = 0.0;
        length_of_horizontal_gap = 0;
    }

    DpOutput {
        maxi,
        maxj,
        // QUIRK(3): score is v[n-1], NOT the value at (maxi, maxj).
        score: v[n - 1],
        pointers,
        lengths,
    }
}

/// Shared traceback (verbatim port). Handles STOP and (banded-only)
/// DIRECTION_INIT early termination.
fn traceback(a1: &[u8], a2: &[u8], dp: &DpOutput) -> AlignmentResult {
    let n = a2.len() + 1;
    let mut i = dp.maxi;
    let mut j = dp.maxj;
    let mut row = i * n;

    let maxlen = a1.len() + a2.len();
    let mut rev1: Vec<u8> = Vec::with_capacity(maxlen);
    let mut rev2: Vec<u8> = Vec::with_capacity(maxlen);

    let mut a = a1.len();
    let mut b = a2.len();
    // Tail gap filling down to the traceback start cell.
    if a - i > b - j {
        while a - i > b - j {
            rev1.push(a1[a - 1]);
            rev2.push(GAP);
            a -= 1;
        }
        while b > j {
            rev1.push(a1[a - 1]);
            rev2.push(a2[b - 1]);
            a -= 1;
            b -= 1;
        }
    } else {
        while b - j > a - i {
            rev1.push(GAP);
            rev2.push(a2[b - 1]);
            b -= 1;
        }
        while a > i {
            rev1.push(a1[a - 1]);
            rev2.push(a2[b - 1]);
            a -= 1;
            b -= 1;
        }
    }

    loop {
        let l = row + j;
        match dp.pointers[l] {
            UP => {
                for _ in 0..dp.lengths[l] {
                    i -= 1;
                    rev1.push(a1[i]);
                    rev2.push(GAP);
                    row -= n;
                }
            }
            DIAGONAL => {
                i -= 1;
                j -= 1;
                rev1.push(a1[i]);
                rev2.push(a2[j]);
                row -= n;
            }
            LEFT => {
                for _ in 0..dp.lengths[l] {
                    j -= 1;
                    rev1.push(GAP);
                    rev2.push(a2[j]);
                }
            }
            // STOP and DIRECTION_INIT both end the traceback; QUIRK(6): the
            // banded version can hit DIRECTION_INIT outside the band.
            _ => break,
        }
    }

    rev1.reverse();
    rev2.reverse();
    AlignmentResult {
        aligned1: rev1,
        aligned2: rev2,
        score: dp.score,
        start1: i,
        start2: j,
    }
}

/// Sort so the longer sequence is s1 (rows) — QUIRK(1) — then align.
fn align_sorted(
    s1: &[u8],
    s2: &[u8],
    match_s: f32,
    mismatch: f32,
    o: f32,
    e: f32,
    bandwidth: Option<usize>,
) -> AlignmentResult {
    let (a1, a2) = if s1.len() < s2.len() {
        (s2, s1)
    } else {
        (s1, s2)
    };
    let dp = construct(a1, a2, match_s, mismatch, o, e, bandwidth);
    traceback(a1, a2, &dp)
}

/// NeedlemanWunschGotohBanded.align (MatrixGenerator match/mismatch matrix,
/// gap open `o` / extend `e`, `bandwidth`).
pub fn nw_gotoh_banded(
    s1: &[u8],
    s2: &[u8],
    match_s: f32,
    mismatch: f32,
    gap_open: f32,
    gap_extend: f32,
    bandwidth: usize,
) -> AlignmentResult {
    align_sorted(
        s1,
        s2,
        match_s,
        mismatch,
        gap_open,
        gap_extend,
        Some(bandwidth),
    )
}

/// NeedlemanWunschGotoh.align (unbanded).
pub fn nw_gotoh(
    s1: &[u8],
    s2: &[u8],
    match_s: f32,
    mismatch: f32,
    gap_open: f32,
    gap_extend: f32,
) -> AlignmentResult {
    align_sorted(s1, s2, match_s, mismatch, gap_open, gap_extend, None)
}

/// Port of NWalign.run_NW_alignment: align and collect stats, undoing the
/// QUIRK(1) name swap so stats.count1 refers to `s1` and count2 to `s2`.
pub fn run_nw_alignment(
    s1: &[u8],
    s2: &[u8],
    match_s: f32,
    mismatch: f32,
    open: f32,
    extend: f32,
) -> (AlignmentResult, AlignmentStats) {
    let (aln, origs) = align_with_order(s1, s2, match_s, mismatch, open, extend, None);
    let swapped = s1.len() < s2.len();
    let st = stats_for(&aln, origs, swapped);
    (aln, st)
}

/// Port of NWalign.run_NW_banded_alignment.
pub fn run_nw_banded_alignment(
    s1: &[u8],
    s2: &[u8],
    match_s: f32,
    mismatch: f32,
    open: f32,
    extend: f32,
    bandwidth: usize,
) -> (AlignmentResult, AlignmentStats) {
    let (aln, origs) = align_with_order(s1, s2, match_s, mismatch, open, extend, Some(bandwidth));
    let swapped = s1.len() < s2.len();
    let st = stats_for(&aln, origs, swapped);
    (aln, st)
}

fn align_with_order(
    s1: &[u8],
    s2: &[u8],
    match_s: f32,
    mismatch: f32,
    o: f32,
    e: f32,
    bandwidth: Option<usize>,
) -> (AlignmentResult, (Vec<u8>, Vec<u8>)) {
    // (sorted originals, for compute_stats; count1/count2 refer to these)
    let origs = if s1.len() < s2.len() {
        (s2.to_vec(), s1.to_vec())
    } else {
        (s1.to_vec(), s2.to_vec())
    };
    let aln = align_sorted(s1, s2, match_s, mismatch, o, e, bandwidth);
    (aln, origs)
}

fn stats_for(aln: &AlignmentResult, origs: (Vec<u8>, Vec<u8>), swapped: bool) -> AlignmentStats {
    let mut st = compute_stats(aln, &origs.0, &origs.1);
    if swapped {
        // undo the QUIRK(1) length-sort swap so count1 refers to the caller's s1
        std::mem::swap(&mut st.count1, &mut st.count2);
    }
    st
}

/// Port of AlignmentStats.get_num_left_end_gaps.
pub fn get_num_left_end_gaps(seq: &[u8]) -> usize {
    seq.iter().take_while(|&&c| c == GAP).count()
}

/// Port of AlignmentStats.get_num_right_end_gaps.
pub fn get_num_right_end_gaps(seq: &[u8]) -> usize {
    seq.iter().rev().take_while(|&&c| c == GAP).count()
}

/// Port of the AlignmentStats(Alignment) constructor (NW flavour).
///
/// `orig_s1`/`orig_s2` must be the originals in the same (sorted) order as the
/// alignment's sequences — i.e. pass the longer first, as `align_sorted` does.
/// (The run_* wrappers do the swapping for you.)
pub fn compute_stats(aln: &AlignmentResult, orig_s1: &[u8], orig_s2: &[u8]) -> AlignmentStats {
    let seq1 = &aln.aligned1;
    let seq2 = &aln.aligned2;

    let mut st = AlignmentStats {
        left_bound: compute_left_bound(seq1, seq2),
        ..AlignmentStats::default()
    };
    if st.left_bound < 0 {
        // no aligned bases
        return st;
    }
    st.right_bound = compute_right_bound(seq1, seq2);

    let left_bound = st.left_bound as usize;
    let right_bound = st.right_bound as usize;
    st.alignment_length = right_bound - left_bound + 1;

    let start_pos_a = aln.start1 + 1; // 1-based, as in Java
    let start_pos_b = aln.start2 + 1;

    // Java counts A/B bases over the whole aligned strings (outside-left,
    // inside bounds, outside-right) — net effect: every non-gap column counts.
    let mut a_bases = 0usize;
    let mut b_bases = 0usize;
    for i in 0..seq1.len() {
        if seq1[i] != GAP {
            a_bases += 1;
        }
        if seq2[i] != GAP {
            b_bases += 1;
        }
    }
    st.count1 = a_bases;
    st.count2 = b_bases;

    for i in left_bound..=right_bound {
        let c1 = seq1[i];
        let c2 = seq2[i];
        if c1 == GAP || c2 == GAP {
            st.gaps += 1;
        }
        if c1 != GAP && c2 != GAP {
            if c1 == c2 {
                st.matches += 1;
            } else {
                st.mismatches += 1;
            }
        }
    }

    let end_pos_a = start_pos_a + a_bases - 1;
    let end_pos_b = start_pos_b + b_bases - 1;

    // Terminal gap lengths (verbatim Java arithmetic; the orig-length terms
    // are 0 for a full NW traceback but can matter for truncated banded ones).
    st.right_gap_length = seq1.len() - right_bound - 1;
    st.left_gap_length = left_bound;
    // if SmithWaterman, treat unaligned terminal regions as gaps: Java adds
    // (start_pos_A - 1) + (start_pos_B - 1) to the left gap length.
    st.left_gap_length += (start_pos_a - 1) + (start_pos_b - 1);
    st.right_gap_length +=
        (orig_s1.len().saturating_sub(end_pos_a)) + (orig_s2.len().saturating_sub(end_pos_b));

    // Internal gap lengths.
    let mut gap_len1 = 0usize;
    let mut gap_len2 = 0usize;
    for i in left_bound..=right_bound {
        if seq1[i] == GAP {
            gap_len1 += 1;
        } else {
            st.max_internal_gap_length = st.max_internal_gap_length.max(gap_len1);
            gap_len1 = 0;
        }
        if seq2[i] == GAP {
            gap_len2 += 1;
        } else {
            st.max_internal_gap_length = st.max_internal_gap_length.max(gap_len2);
            gap_len2 = 0;
        }
    }

    st.total_not_matched = st.mismatches + st.gaps + st.left_gap_length + st.right_gap_length;
    st
}

fn compute_left_bound(seq1: &[u8], seq2: &[u8]) -> i64 {
    for i in 0..seq1.len() {
        if seq1[i] != GAP && seq2[i] != GAP {
            return i as i64;
        }
    }
    -1
}

fn compute_right_bound(seq1: &[u8], seq2: &[u8]) -> i64 {
    for i in (0..seq1.len()).rev() {
        if seq1[i] != GAP && seq2[i] != GAP {
            return i as i64;
        }
    }
    seq1.len() as i64
}

/// Port of AlignmentStats.get_max_diffs_in_window.
pub fn get_max_diffs_in_window(aln: &AlignmentResult, window_size: usize) -> usize {
    let seq1 = &aln.aligned1;
    let seq2 = &aln.aligned2;
    let left_bound = compute_left_bound(seq1, seq2);
    if left_bound < 0 {
        return 0;
    }
    let right_bound = compute_right_bound(seq1, seq2);
    let (lb, rb) = (left_bound as usize, right_bound as usize);

    let mut max_diffs = 0usize;
    let mut num_diffs = 0i64;
    for i in lb..=rb {
        if seq1[i] != seq2[i] {
            num_diffs += 1;
        }
        let left_win_pos = i as i64 - window_size as i64;
        if left_win_pos >= lb as i64 && seq1[left_win_pos as usize] != seq2[left_win_pos as usize] {
            num_diffs -= 1; // this diff is now outside the window
        }
        if num_diffs > max_diffs as i64 {
            max_diffs = num_diffs as usize;
        }
    }
    max_diffs
}

/// Port of AlignmentStats.increment_alignment_stats.
pub fn increment_alignment_stats(a: &AlignmentStats, b: &AlignmentStats) -> AlignmentStats {
    AlignmentStats {
        matches: a.matches + b.matches,
        mismatches: a.mismatches + b.mismatches,
        gaps: a.gaps + b.gaps,
        alignment_length: a.alignment_length + b.alignment_length,
        max_internal_gap_length: a.max_internal_gap_length.max(b.max_internal_gap_length),
        total_not_matched: a.total_not_matched + b.total_not_matched,
        ..AlignmentStats::default()
    }
}

/// Port of ZipperAlignment.doZipperAlignmentAnchorLeft.
pub fn zipper_anchor_left(s1: &[u8], s2: &[u8]) -> AlignmentStats {
    let (shorter_len, longer_len) = if s1.len() < s2.len() {
        (s1.len(), s2.len())
    } else {
        (s2.len(), s1.len())
    };
    let mut as_ = AlignmentStats {
        count1: shorter_len,
        count2: shorter_len,
        ..Default::default()
    };
    for i in 0..shorter_len {
        if s1[i] == s2[i] {
            as_.matches += 1;
        } else {
            as_.mismatches += 1;
        }
    }
    as_.right_gap_length = longer_len - shorter_len;
    as_.total_not_matched = as_.right_gap_length;
    as_
}

/// Port of ZipperAlignment.doZipperAlignmentAnchorRight. QUIRK(8): the Java
/// loop decrements both i and j but compares `seqA.charAt(i) == seqB.charAt(i)`
/// (index i for BOTH sequences) — bug kept verbatim.
pub fn zipper_anchor_right(s1: &[u8], s2: &[u8]) -> AlignmentStats {
    let (shorter_len, longer_len) = if s1.len() < s2.len() {
        (s1.len(), s2.len())
    } else {
        (s2.len(), s1.len())
    };
    let mut as_ = AlignmentStats {
        count1: shorter_len,
        count2: shorter_len,
        ..Default::default()
    };
    let mut i = shorter_len as i64 - 1;
    let mut j = longer_len as i64 - 1;
    while i >= 0 && j >= 0 {
        // QUIRK(8): both indexed by i, exactly as in Java.
        if s1[i as usize] == s2[i as usize] {
            as_.matches += 1;
        } else {
            as_.mismatches += 1;
        }
        i -= 1;
        j -= 1;
    }
    as_.left_gap_length = longer_len - shorter_len;
    as_.total_not_matched = as_.left_gap_length;
    as_
}

/// Port of ZipperAlignment.doZipperAlignment: prefers the left anchor on strict
/// `>`; ties go to the right anchor.
pub fn zipper_align(s1: &[u8], s2: &[u8]) -> AlignmentStats {
    let left = zipper_anchor_left(s1, s2);
    let right = zipper_anchor_right(s1, s2);
    if left.matches > right.matches {
        left
    } else {
        right
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identical_sequences_score_and_align() {
        let a = nw_gotoh(b"ACGTACGT", b"ACGTACGT", 4.0, -5.0, 10.0, 1.0);
        assert_eq!(a.aligned1, b"ACGTACGT");
        assert_eq!(a.aligned2, b"ACGTACGT");
        assert_eq!(a.score, 32.0);
        assert_eq!((a.start1, a.start2), (0, 0));
    }

    #[test]
    fn longer_sequence_becomes_rows_and_names_swap() {
        // s1 shorter: the run_NW_* wrappers must swap count1/count2 back so
        // count1 refers to the caller's s1 (QUIRK 1).
        let (_aln, st) = run_nw_alignment(b"ACGT", b"ACGTACGT", 4.0, -5.0, 10.0, 1.0);
        assert_eq!(st.count1, 4); // caller's s1
        assert_eq!(st.count2, 8); // caller's s2
    }

    #[test]
    fn row_end_vdiagonal_reset_quirk() {
        // QUIRK 4: vDiagonal resets to 0 at each row start, so cell (i,1)
        // computes f = 0 + match instead of building on the first-column value
        // v[0] = -o - (i-1)e. Textbook Gotoh would score this alignment
        // negative; the port (like Java) reports the loose 4.0.
        let a = nw_gotoh(b"AAAA", b"A", 4.0, -5.0, 10.0, 1.0);
        assert_eq!(a.score, 4.0);
        assert_eq!(a.aligned1, b"AAAA");
        assert_eq!(a.aligned2, b"A---");
    }

    #[test]
    fn tail_gap_filling() {
        // Traceback starts at (maxi, maxj) which can be below the last
        // column/row; the suffix is filled with terminal gaps before walking.
        let a = nw_gotoh(b"ACGTACGTACGT", b"ACGTAC", 4.0, -5.0, 10.0, 1.0);
        assert_eq!(a.aligned1, b"ACGTACGTACGT");
        assert_eq!(a.aligned2, b"ACGTAC------");
    }

    #[test]
    fn banded_traceback_stops_at_direction_init() {
        // QUIRK 6: with bandwidth 2 (half=1), a LEFT move at the band's left
        // edge steps outside the band where pointers stay DIRECTION_INIT, so
        // the traceback stops early and the aligned strings cover only the
        // suffix (start1=2, start2=3). Verified identical in the Java jar.
        let b = nw_gotoh_banded(b"CCCCAC", b"AAACA", 4.0, -5.0, 10.0, 1.0, 2);
        assert_eq!(b.aligned1, b"CCAC");
        assert_eq!(b.aligned2, b"-CA-");
        assert_eq!(b.score, -5.0);
        assert_eq!((b.start1, b.start2), (2, 3));
        // The unbanded alignment covers everything, by contrast.
        let f = nw_gotoh(b"CCCCAC", b"AAACA", 4.0, -5.0, 10.0, 1.0);
        assert_eq!((f.start1, f.start2), (0, 0));
        assert_eq!(f.aligned1.len(), 9);
    }

    #[test]
    fn banded_matches_full_when_band_is_wide() {
        let s1 = b"ACGTACGTACGTACGTACGT";
        let s2 = b"ACGTTCGTACGTACGTACGA";
        for bw in [10usize, 20, 40] {
            let a = nw_gotoh_banded(s1, s2, 4.0, -5.0, 10.0, 1.0, bw);
            let b = nw_gotoh(s1, s2, 4.0, -5.0, 10.0, 1.0);
            assert_eq!(a.aligned1, b.aligned1, "bw={bw}");
            assert_eq!(a.aligned2, b.aligned2, "bw={bw}");
            assert_eq!(a.score.to_bits(), b.score.to_bits(), "bw={bw}");
        }
    }

    #[test]
    fn f32_tie_horizontal_gap_prefers_extension() {
        // QUIRK 5 (h - e >= v[j-1] - o prefers extending) plus the f32 `==`
        // tie ordering are exercised end-to-end by the golden test; here we
        // pin the tie-sensitive alignment of a homopolymer indel.
        let a = nw_gotoh(
            b"AAAAACCCCCGGGGG",
            b"AAAAACCCCCCGGGGG",
            4.0,
            -5.0,
            10.0,
            1.0,
        );
        // single-nucleotide insertion -> exactly one gap column overall
        // (the Java traceback places it as a leading gap in the shorter read)
        let g1 = a.aligned1.iter().filter(|&&c| c == GAP).count();
        let g2 = a.aligned2.iter().filter(|&&c| c == GAP).count();
        assert_eq!(g1 + g2, 1);
        assert_eq!(a.score, 51.0);
    }

    #[test]
    fn n_matches_everything_quirk() {
        // MatrixGenerator: i=='N' || j=='N' scores as match.
        let a = nw_gotoh(b"ACN", b"ACG", 4.0, -5.0, 10.0, 1.0);
        assert_eq!(a.score, 12.0);
        assert_eq!(a.aligned1, b"ACN");
        assert_eq!(a.aligned2, b"ACG");
    }

    #[test]
    fn stats_manual_computation() {
        // Hand-computed stats for an alignment with terminal and internal gaps:
        //   idx:  0  1  2  3  4  5  6  7  8  9  10 11
        //   s1:   -  -  A  C  G  -  T  T  A  -  -  -
        //   s2:   G  G  A  C  G  A  T  T  A  A  A  -
        let aln = AlignmentResult {
            aligned1: b"--ACG-TTA---".to_vec(),
            aligned2: b"GGACGATTAAA-".to_vec(),
            score: 0.0,
            start1: 0,
            start2: 0,
        };
        let st = compute_stats(&aln, b"ACGTTA", b"GGACGATTAAA");
        assert_eq!(st.left_bound, 2);
        assert_eq!(st.right_bound, 8);
        assert_eq!(st.alignment_length, 7);
        // cols 2..8: A/A C/C G/G -/A T/T T/T A/A
        assert_eq!(st.matches, 6);
        assert_eq!(st.mismatches, 0);
        assert_eq!(st.gaps, 1); // only col 5 (-/A) lies within the bounds
        assert_eq!(st.max_internal_gap_length, 1);
        assert_eq!(st.left_gap_length, 2); // 2 leading all-gap-on-one-side cols
        assert_eq!(st.right_gap_length, 3); // 12 - 8 - 1
        assert_eq!(st.total_not_matched, 1 + 2 + 3);
        assert_eq!(st.count1, 6); // ACGTTA
        assert_eq!(st.count2, 11); // GGACGATTAAA
    }

    #[test]
    fn stats_counts_end_gaps_helpers() {
        assert_eq!(get_num_left_end_gaps(b"--AAC"), 2);
        assert_eq!(get_num_left_end_gaps(b"AC--"), 0);
        assert_eq!(get_num_right_end_gaps(b"AC--"), 2);
        assert_eq!(get_num_right_end_gaps(b"--AC"), 0);
        assert_eq!(get_num_left_end_gaps(b"----"), 4);
    }

    #[test]
    fn zipper_left_right_anchors_and_tie() {
        // Left anchor: positional comparison, right_gap = diff.
        let st = zipper_align(b"ACGT", b"ACGT");
        // equal matches -> tie goes to the RIGHT anchor (Java `>`).
        assert_eq!(st.left_gap_length, 0);
        assert_eq!(st.right_gap_length, 0);
        assert_eq!(st.matches, 4);

        // Left and right anchors tie at 4 matches here, so the RIGHT anchor
        // wins (Java: `left.matches > right.matches` only) -> left_gap = 4.
        let st = zipper_align(b"ACGTAAAA", b"ACGT");
        assert_eq!(st.matches, 4);
        assert_eq!(st.right_gap_length, 0); // right anchor chosen on the tie
        assert_eq!(st.left_gap_length, 4);
        assert_eq!(st.total_not_matched, 4);

        // QUIRK 8: anchor-right compares seqA[i] == seqB[i] (both by i).
        // Correct right-anchoring of s1="GT" into s2="AAGT" would match "GT"
        // (2 matches), but the quirk compares B[i]: G vs A, T vs A -> 0
        // matches. Left anchor also scores 0 -> tie -> right anchor returned.
        let st = zipper_align(b"GT", b"AAGT");
        assert_eq!(st.matches, 0, "quirk 8: right anchor indexes both by i");
        assert_eq!(st.left_gap_length, 2);
        assert_eq!(st.total_not_matched, 2);
    }
}
